### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by willgdjones** [AntixK/PyTorch-VAE#1]
New to pytorch and I'm looking to run your work but I'm encountering the error when when I set `download=True` in the appropriate locations in the `experiment.py` to download the celeba datasets I'm encountering this error:

```
Traceback (most recent call last):
  File "run.py", line 55, in <module>
    runner.fit(experiment)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 602, in fit
    self.single_gpu_train(model)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 470, in single_gpu_train
    self.run_pretrain_routine(model)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 796, in run_pretrain_routine
    self.reset_val_dataloader(ref_model)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/pytorch_lightning/trainer/data_loading.py", line 154, in reset_val_dataloader
    self.val_dataloaders = self.request_data_loader(model.val_dataloader)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/pytorch_lightning/trainer/data_loading.py", line 220, in request_data_loader
    data_loader = data_loader_fx()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/pytorch_lightning/core/decorators.py", line 16, in inner_fx
    return fn(self)
  File "/home/ubuntu/PyTorch-VAE/experiment.py", line 161, in val_dataloader
    download=True),
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torchvision/datasets/celeba.py", line 63, in __init__
    self.download()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torchvision/datasets/celeba.py", line 117, in download
    with zipfile.ZipFile(os.path.join(self.root, self.base_folder, "img_align_celeba.zip"), "r") as f:
  File "/home/ubuntu/anaconda3/lib/python3.6/zipfile.py", line 1108, in __init__
    self._RealGetContents()
  File "/home/ubuntu/anaconda3/lib/python3.6/zipfile.py", line 1175, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

Running on Ubuntu Deep Learning AMI instance with `torch==1.3.1` and `torchvision==0.4.2`.

Would appreciate any help you can give! Thanks a lot.

**Comment by AntixK** [comment]
Seems like the downloaded dataset is corrupted, possibly due to [Google Drive traffic](https://github.com/pytorch/vision/issues/1920). 
You can simply download the celeba dataset from [here](http://mmlab.ie.cuhk.edu.hk/projects/CelebA.html) and just link its path to the config file.
Hope this helps!

**Comment by willgdjones** [comment]
Thanks! I will try that. How should I specify it in the config file?

**Comment by AntixK** [comment]
Download the dataset and extract it anywhere you want. (You can now set the download to be False in the experiment.py)
Set the path to the dataset in the `data_path:` variable in the config file. Check out the config file template in the readme for more details.

**Comment by zara0m** [comment]
> Download the dataset and extract it anywhere you want. (You can now set the download to be False in the experiment.py)
> Set the path to the dataset in the `data_path:` variable in the config file. Check out the config file template in the readme for more details.

I had the same problem and I set the path of dataset in vae.config but still I got this error:

RuntimeError: Dataset not found or corrupted. You can use download=True to download it
