### ISSUE TITLE
Torch Issue

### ISSUE THREAD

**Issue by francisbitontistudio** [AntixK/PyTorch-VAE#42]
I am trying to run this repo for the first time. I am getting the following error. Torch is installed and I am able to import torch outside of this script. Has anyone experienced a similar issue? 
```
Traceback (most recent call last):
  File "run.py", line 5, in <module>
    from models import *
  File "D:\github\PyTorch-VAE\models\__init__.py", line 1, in <module>
    from .base import *
  File "D:\github\PyTorch-VAE\models\base.py", line 2, in <module>
    from torch import nn
ModuleNotFoundError: No module named 'torch'
```

**Comment by AntixK** [comment]
Please install pytorch from here - https://pytorch.org/
